### ISSUE TITLE
AUR disown?

### ISSUE THREAD

**Issue by SanskritFritz** [bseb/cntlm#1]
Why? I'm willing to maintain, but it depends on this repo. Will this stay?

**Comment by bseb** [comment]
I am no longer using Arch Linux, and I was mostly just hosting the code so it didn't have to come from sourceforge.

I have no plans to delete this repo, however I would suggest considering pointing the aur package to your fork, as it will be easier for you to maintain and update as opposed to putting in pull requests to this one.

**Comment by SanskritFritz** [comment]
Thank you for the clarification. Good luck with your journey onwards.
I'll maintain the package according to your advice.

**Comment by SanskritFritz** [comment]
BTW I loved your git history :smiley: 
```
Date:   Sat Dec 5 18:00:35 2015 -0500
    No really, Ive used a computer before

Date:   Sat Dec 5 17:46:01 2015 -0500
    sigh

Date:   Sat Dec 5 17:42:44 2015 -0500
    update .SRCINFO because every update should take 3 commits


```

**Comment by bseb** [comment]
Haha I had forgotten that
